name: Auto Merge PRs for 2025webi.md with Valid Entry

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  pull-requests: write

jobs:
  automerge:
    runs-on: ubuntu-latest
    if: github.event.pull_request.base.ref == 'main'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Fetch PR diff
        id: get_diff
        run: |
          gh pr diff ${{ github.event.pull_request.number }} > diff.txt
          echo "Got diff:"
          cat diff.txt
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check changed files
        id: check_file
        run: |
          changed_files=$(gh pr view ${{ github.event.pull_request.number }} --json files --jq '.files[].path')
          if [ "$changed_files" = "2025webi.md" ]; then
            echo "ONLY_FILE=true" >> $GITHUB_ENV
          else
            echo "ONLY_FILE=false" >> $GITHUB_ENV
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check for valid line in diff
        id: check_line
        run: |
          if grep -qP '^\+ - \[.+\]\(https://github\.com/[a-zA-Z0-9-]+\)' diff.txt; then
            echo "VALID_LINE=true" >> $GITHUB_ENV
          else
            echo "VALID_LINE=false" >> $GITHUB_ENV
          fi

      - name: Merge PR
        if: env.ONLY_FILE == 'true' && env.VALID_LINE == 'true'
        run: gh pr merge ${{ github.event.pull_request.number }} --merge --admin
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
